version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - lookup_zookeeper_data:/var/lib/zookeeper/data
      - lookup_zookeeper_log:/var/lib/zookeeper/log
    networks:
      - lookup
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    depends_on:
      - zookeeper
    volumes:
      - lookup_kafka_data:/var/lib/kafka/data
    networks:
      - lookup
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:19092"
    depends_on:
      - kafka
    networks:
      - lookup
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - lookup
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-requests-distributor:
    build: lookup-requests-distributor/.
    image: lookup-requests-distributor:latest
    container_name: lookup-requests-distributor
    restart: always
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
      SPRING_APPLICATION_NAME: "lookup-requests-distributor"
      SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
    depends_on:
      - kafka
    networks:
      - lookup
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-requests-manager:
    build: lookup-requests-manager/.
    image: lookup-requests-manager:latest
    container_name: lookup-requests-manager
    restart: always
    ports:
      - 9003:8080
    networks:
      - lookup
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
      
volumes:
  lookup_zookeeper_data:
    name: lookup_zookeeper_data
  lookup_zookeeper_log:
    name: lookup_zookeeper_log
  lookup_kafka_data:
    name: lookup_kafka_data

networks:
  lookup:
    name: lookup
