version: "3.9"

services:
  membership-messaging-zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: membership-messaging-zookeeper-1
    restart: always
    hostname: membership-messaging-zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "membership-messaging-zookeeper-1:22888:23888;membership-messaging-zookeeper-2:32888:33888;membership-messaging-zookeeper-3:42888:43888"
    volumes:
      - membership_messaging_zookeeper_1_data:/var/lib/zookeeper/data
      - membership_messaging_zookeeper_1_log:/var/lib/zookeeper/log
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.20

  membership-messaging-zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    container_name: membership-messaging-zookeeper-2
    restart: always
    hostname: membership-messaging-zookeeper-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "membership-messaging-zookeeper-1:22888:23888;membership-messaging-zookeeper-2:32888:33888;membership-messaging-zookeeper-3:42888:43888"
    volumes:
      - membership_messaging_zookeeper_2_data:/var/lib/zookeeper/data
      - membership_messaging_zookeeper_2_log:/var/lib/zookeeper/log
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.21

  membership-messaging-zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    container_name: membership-messaging-zookeeper-3
    restart: always
    hostname: membership-messaging-zookeeper-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "membership-messaging-zookeeper-1:22888:23888;membership-messaging-zookeeper-2:32888:33888;membership-messaging-zookeeper-3:42888:43888"
    volumes:
      - membership_messaging_zookeeper_3_data:/var/lib/zookeeper/data
      - membership_messaging_zookeeper_3_log:/var/lib/zookeeper/log
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.22

  membership-messaging-kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: membership-messaging-kafka-1
    restart: always
    hostname: membership-messaging-kafka-1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://membership-messaging-kafka-1:19092
      KAFKA_ZOOKEEPER_CONNECT: "membership-messaging-zookeeper-1:22181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    depends_on:
      - membership-messaging-zookeeper-1
      - membership-messaging-zookeeper-2
      - membership-messaging-zookeeper-3
    volumes:
      - membership_messaging_kafka_1_data:/var/lib/kafka/data
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.23

  membership-messaging-kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: membership-messaging-kafka-2
    restart: always
    hostname: membership-messaging-kafka-2
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://membership-messaging-kafka-2:29092
      KAFKA_ZOOKEEPER_CONNECT: "membership-messaging-zookeeper-2:32181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    depends_on:
      - membership-messaging-zookeeper-1
      - membership-messaging-zookeeper-2
      - membership-messaging-zookeeper-3
    volumes:
      - membership_messaging_kafka_2_data:/var/lib/kafka/data
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.24

  membership-messaging-kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: membership-messaging-kafka-3
    restart: always
    hostname: membership-messaging-kafka-3
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://membership-messaging-kafka-3:39092
      KAFKA_ZOOKEEPER_CONNECT: "membership-messaging-zookeeper-3:42181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    depends_on:
      - membership-messaging-zookeeper-1
      - membership-messaging-zookeeper-2
      - membership-messaging-zookeeper-3
    volumes:
      - membership_messaging_kafka_3_data:/var/lib/kafka/data
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.25

  membership-messaging-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: membership-messaging-schema-registry
    restart: always
    depends_on:
      - membership-messaging-zookeeper-1
      - membership-messaging-zookeeper-2
      - membership-messaging-zookeeper-3
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: membership-messaging-zookeeper-1:22181
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: "http://localhost:8085"
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.26

  membership-messaging-kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: membership-messaging-kafka-connect
    restart: always
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "membership-messaging-kafka-1:19092"
      CONNECT_REST_PORT: 28082
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-cluster-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-cluster-offset"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-cluster-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://membership-messaging-schema-registry:8085"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://membership-messaging-schema-registry:8085"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
      CONNECT_ZOOKEEPER_CONNECT: "membership-messaging-zookeeper-1:22181"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: brave.kafka.interceptor.TracingProducerInterceptor
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: brave.kafka.interceptor.TracingConsumerInterceptor
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
    volumes:
      - $PWD/kafka-connect-jars:/etc/kafka-connect/jars
    ports:
      - 28082:28082
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.28
      stg0:
          ipv4_address: 172.30.0.50

  membership-messaging-distributor:
    build: lookup-requests-distributor/.
    image: membership-messaging-distributor:latest
    container_name: membership-messaging-distributor
    restart: always
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "membership-messaging-kafka-1:19092"
      SPRING_APPLICATION_NAME: "membership-messaging-distributor"
      SPRING_ZIPKIN_BASE_URL: "http://membership-messaging-zipkin:9411"
    depends_on:
      - membership-messaging-kafka-1
      - membership-messaging-kafka-2
      - membership-messaging-kafka-3
    networks:
      membership-messaging-net:
        ipv4_address: 172.50.0.29

  membership-messaging-manager:
    build: lookup-requests-manager/.
    image: membership-messaging-manager:latest
    container_name: membership-messaging-manager
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://mssql:1433;database=LookUp_DB"
    networks:
      stg0:
          ipv4_address: 172.30.0.51

  membership-messaging-kafdrop:
    image: kafdrop
    container_name: membership-messaging-kafdrop
    restart: always
    environment:
      KAFKA_BROKERCONNECT: "membership-messaging-kafka-1:19092"
    depends_on:
      - membership-messaging-kafka-1
      - membership-messaging-kafka-2
      - membership-messaging-kafka-3
    networks:
       membership-messaging-net:
          ipv4_address: 172.50.0.11

  membership-messaging-zipkin:
    image: openzipkin/zipkin
    container_name: membership-messaging-zipkin
    restart: always
    networks:
      membership-messaging-net:
          ipv4_address: 172.50.0.10

volumes:
  membership_messaging_zookeeper_1_data:
    name: membership_messaging_zookeeper_1_data
  membership_messaging_zookeeper_1_log:
    name: membership_messaging_zookeeper_1_log
  membership_messaging_zookeeper_2_data:
    name: membership_messaging_zookeeper_2_data
  membership_messaging_zookeeper_2_log:
    name: membership_messaging_zookeeper_2_log
  membership_messaging_zookeeper_3_data:
    name: membership_messaging_zookeeper_3_data
  membership_messaging_zookeeper_3_log:
    name: membership_messaging_zookeeper_3_log
  membership_messaging_kafka_1_data:
    name: membership_messaging_kafka_1_data
  membership_messaging_kafka_2_data:
    name: membership_messaging_kafka_2_data
  membership_messaging_kafka_3_data:
    name: membership_messaging_kafka_3_data

networks:
  membership-messaging-net:
    name: membership-messaging-net
    ipam:
      config:
        - subnet: 172.50.0.0/16
  stg0:
    name: stg0
    external: true
