version: "3.9"

services:
  lookup-zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: lookup-zookeeper-1
    restart: always
    hostname: lookup-zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "lookup-zookeeper-1:22888:23888;lookup-zookeeper-2:32888:33888;lookup-zookeeper-3:42888:43888"
    volumes:
      - membership_messaging_zookeeper_1_data:/var/lib/zookeeper/data
      - membership_messaging_zookeeper_1_log:/var/lib/zookeeper/log
    networks:
      stg0:
        ipv4_address: 172.30.0.40
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    container_name: lookup-zookeeper-2
    restart: always
    hostname: lookup-zookeeper-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "lookup-zookeeper-1:22888:23888;lookup-zookeeper-2:32888:33888;lookup-zookeeper-3:42888:43888"
    volumes:
      - membership_messaging_zookeeper_2_data:/var/lib/zookeeper/data
      - membership_messaging_zookeeper_2_log:/var/lib/zookeeper/log
    networks:
      stg0:
        ipv4_address: 172.30.0.49
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    container_name: lookup-zookeeper-3
    restart: always
    hostname: lookup-zookeeper-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: "lookup-zookeeper-1:22888:23888;lookup-zookeeper-2:32888:33888;lookup-zookeeper-3:42888:43888"
    volumes:
      - membership_messaging_zookeeper_3_data:/var/lib/zookeeper/data
      - membership_messaging_zookeeper_3_log:/var/lib/zookeeper/log
    networks:
      stg0:
        ipv4_address: 172.30.0.42
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: lookup-kafka-1
    restart: always
    hostname: lookup-kafka-1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://lookup-kafka-1:19092
      KAFKA_ZOOKEEPER_CONNECT: "lookup-zookeeper-1:22181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      EXTRA_ARGS: -javaagent:/usr/lib/jmx_prometheus_javaagent-0.16.0.jar=1234:/usr/lib/kafka_broker.yml
    depends_on:
      - lookup-zookeeper-1
      - lookup-zookeeper-2
      - lookup-zookeeper-3
    volumes:
      - membership_messaging_kafka_1_data:/var/lib/kafka/data
      - $PWD/config/jmx-exporter/kafka-broker/kafka_broker.yml:/usr/lib/kafka_broker.yml
      - $PWD config/jmx-exporter/jmx_prometheus_javaagent-0.16.0.jar:/usr/lib/jmx_prometheus_javaagent-0.16.0.jar
    networks:
      stg0:
        ipv4_address: 172.30.0.43
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: lookup-kafka-2
    restart: always
    hostname: lookup-kafka-2
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://lookup-kafka-2:29092
      KAFKA_ZOOKEEPER_CONNECT: "lookup-zookeeper-2:32181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      EXTRA_ARGS: -javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.15.0.jar=1234:/opt/prometheus/kafka_broker.yml
    depends_on:
      - lookup-zookeeper-1
      - lookup-zookeeper-2
      - lookup-zookeeper-3
    volumes:
      - membership_messaging_kafka_2_data:/var/lib/kafka/data
      - $PWD/config/jmx-exporter/kafka-broker/kafka_broker.yml:/opt/prometheus/kafka_broker.yml
      - $PWD config/jmx-exporter/jmx_prometheus_javaagent-0.15.0.jar:/opt/prometheus/jmx_prometheus_javaagent-0.15.0.jar
    networks:
      stg0:
        ipv4_address: 172.30.0.44
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: lookup-kafka-3
    restart: always
    hostname: lookup-kafka-3
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://lookup-kafka-3:39092
      KAFKA_ZOOKEEPER_CONNECT: "lookup-zookeeper-3:42181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      EXTRA_ARGS: -javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.15.0.jar=1234:/opt/prometheus/kafka_broker.yml
    depends_on:
      - lookup-zookeeper-1
      - lookup-zookeeper-2
      - lookup-zookeeper-3
    volumes:
      - membership_messaging_kafka_3_data:/var/lib/kafka/data
      - $PWD/config/jmx-exporter/kafka-broker/kafka_broker.yml:/opt/prometheus/kafka_broker.yml
      - $PWD config/jmx-exporter/jmx_prometheus_javaagent-0.15.0.jar:/opt/prometheus/jmx_prometheus_javaagent-0.15.0.jar
    networks:
      stg0:
        ipv4_address: 172.30.0.45
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-distributor:
    build: lookup-requests-distributor/.
    image: lookup-distributor:latest
    container_name: lookup-distributor
    restart: always
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "lookup-kafka-1:19092"
      SPRING_APPLICATION_NAME: "lookup-distributor"
      SPRING_ZIPKIN_BASE_URL: "http://lookup-zipkin:9411"
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://mssql:1433;database=LookUp_DB"
      TOPIC_LOOKUP_REQUESTS_NAME: "mssql.dbo.TRANSACTIONS"
      NEW_TOPIC_DEFAULT_PARTITIONS: 1
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd123
      SPRING_DATASOURCE_username: sa
    depends_on:
      - lookup-kafka-1
      - lookup-kafka-2
      - lookup-kafka-3
    networks:
      stg0:
        ipv4_address: 172.30.0.46
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-manager:
    build: lookup-requests-manager/.
    image: lookup-manager:latest
    container_name: lookup-manager
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://mssql:1433;database=LookUp_DB"
      SUPERVISOR_SERVER_ADDRESS: "container-supervisor:8080"
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd123
      SPRING_DATASOURCE_username: sa
    networks:
      stg0:
        ipv4_address: 172.30.0.47
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  container-supervisor:
    build: container-supervisor/.
    image: container-supervisor:latest
    container_name: container-supervisor
    restart: always
    networks:
      stg0:
        ipv4_address: 172.30.0.48
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-kafdrop:
    image: kafdrop
    container_name: lookup-kafdrop
    restart: always
    environment:
      KAFKA_BROKERCONNECT: "lookup-kafka-1:19092"
    depends_on:
      - lookup-kafka-1
      - lookup-kafka-2
      - lookup-kafka-3
    networks:
      stg0:
        ipv4_address: 172.30.0.54
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  lookup-zipkin:
    image: openzipkin/zipkin
    container_name: lookup-zipkin
    restart: always
    networks:
      stg0:
        ipv4_address: 172.30.0.53
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

volumes:
  membership_messaging_zookeeper_1_data:
    name: membership_messaging_zookeeper_1_data
  membership_messaging_zookeeper_1_log:
    name: membership_messaging_zookeeper_1_log
  membership_messaging_zookeeper_2_data:
    name: membership_messaging_zookeeper_2_data
  membership_messaging_zookeeper_2_log:
    name: membership_messaging_zookeeper_2_log
  membership_messaging_zookeeper_3_data:
    name: membership_messaging_zookeeper_3_data
  membership_messaging_zookeeper_3_log:
    name: membership_messaging_zookeeper_3_log
  membership_messaging_kafka_1_data:
    name: membership_messaging_kafka_1_data
  membership_messaging_kafka_2_data:
    name: membership_messaging_kafka_2_data
  membership_messaging_kafka_3_data:
    name: membership_messaging_kafka_3_data

networks:
  stg0:
    name: stg0
    external: true
